version: 3.1.6-{build}

image:
  - Visual Studio 2013
  - Visual Studio 2017
clone_depth: 1

before_build:
  - cmd:
      if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2013" (
        cd C:\projects\libmodbus\src\win32 &&
        cscript.exe configure.js &&
        curl https://raw.githubusercontent.com/chemeris/msinttypes/master/stdint.h > ..\stdint.h
      ) else (
        cd C:\projects\libmodbus &&
        if "%PLATFORM%"=="cygwin" (
          set CYGWIN_ROOT=C:\cygwin
        ) else (
          set CYGWIN_ROOT=C:\cygwin64
        ) && 
        set PATH=%CYGWIN_ROOT%\bin;%PATH%
      )

platform:
  - Win32
  - x64
  - cygwin
  - cygwin64

matrix:
  exclude:
    - image: Visual Studio 2013
      platform: cygwin
    - image: Visual Studio 2013
      platform: cygwin64
    - image: Visual Studio 2017
      platform: Win32
    - image: Visual Studio 2017
      platform: x64

configuration: Release

build_script:
  - cmd: >
      if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2013" (
        cd C:\projects\libmodbus\src\win32
        C:\WINDOWS\Microsoft.NET\Framework\v3.5\msbuild.exe "%APPVEYOR_BUILD_FOLDER%\src\win32\modbus.vcproj" "/p:Configuration=%CONFIGURATION%" "/p:Platform=%PLATFORM%"
      ) else (
        cd C:\projects\libmodbus
        bash autogen.sh
        bash configure
        bash -c 'make'
      )

test_script:
  # cygwin
  - cmd: cd C:\projects\libmodbus
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - cmd: bash -c 'make check; cat tests/test-suite.log'

after_build:
  - cmd: >
      if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2013" (
        cd C:\projects\libmodbus\src\win32
        7z
        a
        ..\..\modbus.zip
        ..\stdint.h
        ..\modbus.h
        ..\modbus-version.h
        ..\modbus-tcp.h
        ..\modbus-rtu.h
        ".\%PLATFORM%\%CONFIGURATION%\modbus.dll"
        ".\%PLATFORM%\%CONFIGURATION%\modbus.exp"
        ".\%PLATFORM%\%CONFIGURATION%\modbus.lib"
        ".\%PLATFORM%\%CONFIGURATION%\modbus.pdb"
      ) else (
        cd C:\projects\libmodbus
        7z
        a
        modbus.zip
        modbus.h
        modbus-version.h
        modbus-tcp.h
        modbus-rtu.h
        .\.libs\cygmodbus-5.dll
        .\.libs\libmodbus.dll.a
        .\.libs\libmodbus.lai
      )

artifacts:
  - path: modbus.zip
