version: 3.1.6-{build}

image:
  - Visual Studio 2013
  - Visual Studio 2017
clone_depth: 1


before_build:
  - ps: >-
      if($env:PLATFORM -like "cygwin*") {
        $env:CYGWIN_ROOT="C:\$env:PLATFORM"
        $env:PATH="$env:CYGWIN_ROOT\bin;$env:PATH"
      } else {
        cd C:\projects\libmodbus\src\win32
        cscript.exe configure.js
        curl https://raw.githubusercontent.com/chemeris/msinttypes/master/stdint.h -o ..\stdint.h
      }

platform:
  - Win32
  - x64
  - cygwin
  - cygwin64

matrix:
  exclude:
    - image: Visual Studio 2013
      platform: cygwin
    - image: Visual Studio 2013
      platform: cygwin64
    - image: Visual Studio 2017
      platform: Win32
    - image: Visual Studio 2017
      platform: x64

configuration: Release

build_script:
  - ps: >-
      if($env:PLATFORM -like "cygwin*") {
        cd $env:APPVEYOR_BUILD_FOLDER
        bash autogen.sh
        bash configure
        bash -c 'make'
      } else {
        cd $env:APPVEYOR_BUILD_FOLDER\src\win32
        C:\WINDOWS\Microsoft.NET\Framework\v3.5\msbuild.exe "$env:APPVEYOR_BUILD_FOLDER\src\win32\modbus.vcproj" "/p:Configuration=$env:CONFIGURATION" "/p:Platform=$env:PLATFORM"
      }

test_script:
  - ps: >-
      if($env:PLATFORM -like "cygwin*") {
        cd $env:APPVEYOR_BUILD_FOLDER
        bash -c 'make check'
        echo "check was run"
      }

after_build:
  - ps: >-
      cd $env:APPVEYOR_BUILD_FOLDER\src

      if($env:PLATFORM -like "cygwin*") {
        7z `
        a `
        ..\modbus.zip `
        modbus.h `
        modbus-version.h `
        modbus-tcp.h `
        modbus-rtu.h `
        .\.libs\cygmodbus-5.dll `
        .\.libs\libmodbus.dll.a `
        .\.libs\libmodbus.lai `
      } else {
        7z `
        a `
        ..\modbus.zip `
        stdint.h `
        modbus.h `
        modbus-version.h `
        modbus-tcp.h `
        modbus-rtu.h `
        "win32\$env:PLATFORM\$env:CONFIGURATION\modbus.dll" `
        "win32\$env:PLATFORM\$env:CONFIGURATION\modbus.exp" `
        "win32\$env:PLATFORM\$env:CONFIGURATION\modbus.lib" `
        "win32\$env:PLATFORM\$env:CONFIGURATION\modbus.pdb"
      }

artifacts:
  - path: modbus.zip
