version: 3.1.6-{build}

image: Visual Studio 2013
clone_depth: 1

before_build:
  # cygwin
  - cmd: cd C:\projects\libmodbus
  - cmd: if %PLATFORM%==Win32 set CYGWIN_ROOT=C:\cygwin64 else set CYGWIN_ROOT=C:\cygwin
  - cmd: set PATH=%CYGWIN_ROOT%\bin;%PATH%
  - cmd: bash -c 'ls /bin'
  - cmd: bash -c 'ln -s /bin/autoreconf-2.69 /bin/autoreconf'
  # msvc
  - cmd: cd C:\projects\libmodbus\src\win32
  - cmd: cscript.exe configure.js
  - cmd: curl https://raw.githubusercontent.com/chemeris/msinttypes/master/stdint.h > ..\stdint.h

platform:
  - Win32
  - x64

configuration: Release

# the normal build way uses a too new msbuild which fails with the current files
build_script:
  # cygwin
  - cmd: cd C:\projects\libmodbus
  - cmd: bash autogen.sh
  - cmd: bash configure
  - cmd: bash -c 'make'
  # msvc
  - cmd: cd C:\projects\libmodbus\src\win32
  - cmd: C:\WINDOWS\Microsoft.NET\Framework\v3.5\msbuild.exe "%APPVEYOR_BUILD_FOLDER%\src\win32\modbus.vcproj" "/p:Configuration=%CONFIGURATION%" "/p:Platform=%PLATFORM%"

test_script:
  - cmd: bash -c 'make check'

after_build:
  - cmd: cd C:\projects\libmodbus\src\win32
  - cmd: >
      7z
      a
      modbus.zip
      ..\stdint.h
      ..\modbus.h
      ..\modbus-version.h
      ..\modbus-tcp.h
      ..\modbus-rtu.h
      ".\%PLATFORM%\%CONFIGURATION%\modbus.dll"
      ".\%PLATFORM%\%CONFIGURATION%\modbus.exp"
      ".\%PLATFORM%\%CONFIGURATION%\modbus.lib"
      ".\%PLATFORM%\%CONFIGURATION%\modbus.pdb"
  - cmd: dir /s C:\projects\libmodbus

artifacts:
  - path: src\win32\modbus.zip
