image: Visual Studio 2015
clone_depth: 5

before_build:
  - cmd: cd C:\projects\libmodbus\src\win32
  - cmd: cscript.exe configure.js
  - cmd: "\"%VS100COMNTOOLS%\\vcupgrade\" /overwrite modbus.vcproj"

platform:
  - x86
  - x64

configuration: Release

build:
  parallel: true
  project: src\win32\modbus.vcxproj

after_build:
  - cmd: 7z a modbus.zip modbus.dll modbus.dll.manifest modbus.exp modbus.lib modbus.pdb ../modbus.h ../modbus-version.h

artifacts:
  - path: src\win32\modbus.zip

